export const azureLogos = [
  {
    id: "vm",
    label: "Azure Virtual Machines",
    src: "/Azure-icons/compute/10021-icon-service-Virtual-Machine.svg",
    href: "https://learn.microsoft.com/ja-jp/azure/virtual-machines/overview",
  },
  {
    id: "aks",
    label: "Azure Kubernetes Service",
    src: "/Azure-icons/compute/10023-icon-service-Kubernetes-Services.svg",
    href: "https://learn.microsoft.com/ja-jp/azure/aks/intro-kubernetes",
  },
  {
    id: "functions",
    label: "Azure Functions",
    src: "/Azure-icons/compute/10029-icon-service-Function-Apps.svg",
    href: "https://learn.microsoft.com/ja-jp/azure/azure-functions/functions-overview",
  },
  {
    id: "appservice",
    label: "Azure App Service",
    src: "/Azure-icons/compute/10035-icon-service-App-Services.svg",
    href: "https://learn.microsoft.com/ja-jp/azure/app-service/overview",
  },
  {
    id: "cosmos",
    label: "Azure Cosmos DB",
    src: "/Azure-icons/databases/10121-icon-service-Azure-Cosmos-DB.svg",
    href: "https://learn.microsoft.com/ja-jp/azure/cosmos-db/introduction",
  },
  {
    id: "storage",
    label: "Azure Storage",
    src: "/Azure-icons/storage/10086-icon-service-Storage-Accounts.svg",
    href: "https://learn.microsoft.com/ja-jp/azure/storage/common/storage-account-overview",
  },
  {
    id: "monitor",
    label: "Azure Monitor",
    src: "/Azure-icons/monitor/00001-icon-service-Monitor.svg",
    href: "https://learn.microsoft.com/ja-jp/azure/azure-monitor/overview",
  },
  {
    id: "devops",
    label: "Azure DevOps",
    src: "/Azure-icons/devops/10261-icon-service-Azure-DevOps.svg",
    href: "https://learn.microsoft.com/ja-jp/azure/devops/user-guide/what-is-azure-devops",
  },
  {
    id: "firewall",
    label: "Azure Firewall",
    src: "/Azure-icons/networking/10084-icon-service-Firewalls.svg",
    href: "https://learn.microsoft.com/ja-jp/azure/firewall/overview",
  },
  {
    id: "keyvault",
    label: "Azure Key Vault",
    src: "/Azure-icons/security/10245-icon-service-Key-Vaults.svg",
    href: "https://learn.microsoft.com/ja-jp/azure/key-vault/general/overview",
  },
  {
    id: "appgateway",
    label: "Azure Application Gateway",
    src: "/Azure-icons/networking/10076-icon-service-Application-Gateways.svg",
    href: "https://learn.microsoft.com/ja-jp/azure/application-gateway/overview",
  },
  {
    id: "sentinel",
    label: "Microsoft Sentinel",
    src: "/Azure-icons/security/10248-icon-service-Azure-Sentinel.svg",
    href: "https://learn.microsoft.com/ja-jp/azure/sentinel/overview",
  },
  {
    id: "logicapps",
    label: "Azure Logic Apps",
    src: "/Azure-icons/integration/02631-icon-service-Logic-Apps.svg",
    href: "https://learn.microsoft.com/ja-jp/azure/logic-apps/logic-apps-overview",
  },
  {
    id: "servicebus",
    label: "Azure Service Bus",
    src: "/Azure-icons/integration/10836-icon-service-Azure-Service-Bus.svg",
    href: "https://learn.microsoft.com/ja-jp/azure/service-bus-messaging/service-bus-messaging-overview",
  },
  {
    id: "containerinstances",
    label: "Azure Container Instances",
    src: "/Azure-icons/containers/10104-icon-service-Container-Instances.svg",
    href: "https://learn.microsoft.com/ja-jp/azure/container-instances/container-instances-overview",
  },
  {
    id: "containerregistries",
    label: "Azure Container Registry",
    src: "/Azure-icons/containers/10105-icon-service-Container-Registries.svg",
    href: "https://learn.microsoft.com/ja-jp/azure/container-registry/container-registry-intro",
  },
  {
    id: "openai",
    label: "Azure OpenAI",
    src: "/Azure-icons/ai%20+%20machine%20learning/03438-icon-service-Azure-OpenAI.svg",
    href: "https://learn.microsoft.com/ja-jp/azure/ai-services/openai/overview",
  },
  {
    id: "eventgrid",
    label: "Azure Event Grid",
    src: "/Azure-icons/integration/10206-icon-service-Event-Grid-Topics.svg",
    href: "https://learn.microsoft.com/ja-jp/azure/event-grid/overview",
  },
  {
    id: "appinsights",
    label: "Application Insights",
    src: "/Azure-icons/monitor/00012-icon-service-Application-Insights.svg",
    href: "https://learn.microsoft.com/ja-jp/azure/azure-monitor/app/app-insights-overview",
  },
  {
    id: "bastion",
    label: "Azure Bastion",
    src: "/Azure-icons/networking/02422-icon-service-Bastions.svg",
    href: "https://learn.microsoft.com/ja-jp/azure/bastion/bastion-overview",
  },
];
